# Generated by Django 5.0.6 on 2024-06-12 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="author",
        ),
    ]
